version: 2.1                                                 #This is the circleci platform version

orbs:
  docker: circleci/docker@2.6.0

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKERHUB_USERNAME/orb-test
          auth:
            username: $DOCKERHUB_USERNAME                   # This line is Docker credentials for authenticated pulls.
            password: $DOCKERHUB_PASSWORD                   # They can be set as a context in the Organization Settings.
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKERHUB_USERNAME/orb-test
          auth:
            username: $DOCKERHUB_USERNAME                   # This line is Docker credentials for authenticated pulls.
            password: $DOCKERHUB_PASSWORD                   # They can be set as a context in the Organization Settings.
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
      
  #                                                   #This is how jobs are defined
  # build-and-test:
  #   docker:                         # This specifies Docker as the execution environment for our job (hello-job).
  #     - image: cimg/node:lts          # This is the primary container in which your job's commands are run.
  #       auth:
  #         username: $DOCKERHUB_USERNAME                   # This line is Docker credentials for authenticated pulls.
  #         password: $DOCKERHUB_PASSWORD                   # They can be set as a context in the Organization Settings.
  #   steps:
  #     - checkout                                           # check out the code in the project directory
  #     - run: echo "Hello World. I am the product of a successful build."      # run the `echo` command

workflows:                                                 # Workflow defines a list of jobs and they run in the order which they are written.
  commit:                                         # Name of workflow
    jobs:
      - build-and-push                                          # Name of job run
