version: 2.1
orbs:
  docker: circleci/docker@2.6.0
  discord: antonioned/discord@0.1.0

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/base:2024.05
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $REGISTRY/$PROJECT:$TAG ./weather_app/
      - run:
          name: Run Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker run -d --name test_container $REGISTRY/$PROJECT:$TAG
            docker exec -it test_container python3 tests/website_connectivity_unittest.py
      - run:
          name: Push application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo $REGISTRY_PASSWORD | docker login $REGISTRY -u $REGISTRY_USERNAME --password-stdin
            docker push $REGISTRY/$PROJECT:$TAG
      - discord/status:
          fail_only: false
          failure_message: "**${CIRCLE_USERNAME}**'s build: **${CIRCLE_JOB}** failed."
          success_message: "**${CIRCLE_USERNAME}** deployed api to prod."
          webhook: "${DISCORD_STATUS_WEBHOOK}"
